s = [ 'mango' , 'bananna' , 'cherry' , 'guava']
print (s)
marks = []
z = int (input("enter marks1:"))
marks.append(z)
x = int (input("enter marks2:"))
marks.append(x)
c = int (input("enter marks3:"))
marks.append(c)
v = int (input("enter marks4:"))
marks.append(v)
b = int (input("enter marks5:"))
marks.append(b)
n = int (input("enter marks6:"))
marks.append(n)
m= int (input("enter marks7:"))
marks.append(m)
marks.sort()
print(marks)